"""commit updates models

Revision ID: f3662f12147d
Revises: 7ed5aea9397e
Create Date: 2024-11-27 19:57:55.708084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3662f12147d'
down_revision: Union[str, None] = '7ed5aea9397e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
