version: '3.8'

services:
  main_app:
    build: .
    expose:
      - "8080"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - network
      - shared-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    networks:
      - network
      - shared-network

networks:
  shared-network:
    external: true
  network:
    driver: bridge
    external: true